# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import politicalplaces.fields


class Migration(migrations.Migration):

    dependencies = [
        ('politicalplaces', '0006_mapitem_parent'),
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLocationMultiPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place1', politicalplaces.fields.PlaceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mylocation_places1', to='politicalplaces.PoliticalPlace')),
                ('place2', politicalplaces.fields.PlaceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mylocation_places2', to='politicalplaces.PoliticalPlace')),
            ],
        ),
    ]
