# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import politicalplaces.fields


class Migration(migrations.Migration):

    dependencies = [
        ('politicalplaces', '0007_auto_20170315_1728'),
        ('example', '0003_auto_20170309_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLocationComplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory_charfield', models.CharField(max_length=200)),
                ('place', politicalplaces.fields.PlaceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='politicalplaces.PoliticalPlace')),
            ],
        ),
    ]
