# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_mylocationcomplex'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLocationInlineNotPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('parent_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.MyLocation')),
            ],
        ),
    ]
