# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politicalplaces', '0005_auto_20170119_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='politicalplaces.MapItem'),
        ),
    ]
