# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politicalplaces', '0006_mapitem_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalplace',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='politicalplace',
            name='neighborhood_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='politicalplace_neighborhood_set', to='politicalplaces.MapItem'),
        ),
        migrations.AddField(
            model_name='politicalplace',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='politicalplace',
            name='street_address_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='politicalplace_street_address_set', to='politicalplaces.MapItem'),
        ),
    ]
