# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicalplaces', '0007_auto_20170315_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='politicalplace',
            old_name='street_address',
            new_name='route',
        ),
        migrations.RemoveField(
            model_name='politicalplace',
            name='street_address_item',
        ),
        migrations.AddField(
            model_name='politicalplace',
            name='street_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
