# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politicalplaces', '0009_politicalplace_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalplace',
            name='self_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='politicalplace_self_set', to='politicalplaces.MapItem'),
        ),
    ]
