# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicalplaces', '0010_politicalplace_self_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapitem',
            name='error_log',
            field=models.TextField(blank=True),
        ),
    ]
