# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicalplaces', '0011_mapitem_error_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapitem',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
