# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politicalplaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapitem',
            old_name='name',
            new_name='long_name',
        ),
    ]
