# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicalplaces', '0003_auto_20170116_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalplace',
            name='continent',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
