# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicalplaces', '0004_politicalplace_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapitem',
            name='place_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
